# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Blurry_config = debug
  GLFW_config = debug
  GLAD_config = debug
  GLM_config = debug
endif
ifeq ($(config),release)
  Blurry_config = release
  GLFW_config = release
  GLAD_config = release
  GLM_config = release
endif

PROJECTS := Blurry GLFW GLAD GLM

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Blurry: GLFW GLM GLAD
ifneq (,$(Blurry_config))
	@echo "==== Building Blurry ($(Blurry_config)) ===="
	@${MAKE} --no-print-directory -C . -f Blurry.make config=$(Blurry_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C libs -f GLFW.make config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C libs -f GLAD.make config=$(GLAD_config)
endif

GLM:
ifneq (,$(GLM_config))
	@echo "==== Building GLM ($(GLM_config)) ===="
	@${MAKE} --no-print-directory -C libs -f GLM.make config=$(GLM_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Blurry.make clean
	@${MAKE} --no-print-directory -C libs -f GLFW.make clean
	@${MAKE} --no-print-directory -C libs -f GLAD.make clean
	@${MAKE} --no-print-directory -C libs -f GLM.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Blurry"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo "   GLM"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"